openapi: 3.0.0
info:
  description: Socket alerts API endpoints.
  title: Socket alerts repo-labels API
  version: '0'
servers:
- url: https://api.socket.dev/v0
tags:
- name: repo-labels
paths:
  /orgs/{org_slug}/repos/labels/{label_id}/associate:
    post:
      tags:
      - repo-labels
      summary: Associate repository label (beta)
      operationId: associateOrgRepoLabel
      security:
      - bearerAuth:
        - repo-label:update
      - basicAuth:
        - repo-label:update
      description: 'Associate a repository label with a repository.


        Labels can be used to group and organize repositories and to apply security/license policies.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:update'
  /orgs/{org_slug}/repos/labels:
    post:
      tags:
      - repo-labels
      summary: Create repository label (beta)
      operationId: createOrgRepoLabel
      security:
      - bearerAuth:
        - repo-label:create
      - basicAuth:
        - repo-label:create
      description: 'Create a repository label.


        Labels can be used to group and organize repositories and to apply security/license policies.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:create'
    get:
      tags:
      - repo-labels
      summary: List repository labels (beta)
      operationId: getOrgRepoLabelList
      security:
      - bearerAuth:
        - repo-label:list
      - basicAuth:
        - repo-label:list
      description: 'Lists repository labels for the specified organization.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:list'
  /orgs/{org_slug}/repos/labels/{label_id}:
    delete:
      tags:
      - repo-labels
      summary: Delete repository label (beta)
      operationId: deleteOrgRepoLabel
      security:
      - bearerAuth:
        - repo-label:delete
      - basicAuth:
        - repo-label:delete
      description: 'Delete a repository label and all of its associations (repositories, security policy, license policy, etc.).


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:delete'
    get:
      tags:
      - repo-labels
      summary: Get repository label (beta)
      operationId: getOrgRepoLabel
      security:
      - bearerAuth:
        - repo-label:list
      - basicAuth:
        - repo-label:list
      description: 'Retrieve a repository label associated with an organization and label ID.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:list'
    put:
      tags:
      - repo-labels
      summary: Update repository label (beta)
      operationId: updateOrgRepoLabel
      security:
      - bearerAuth:
        - repo-label:update
      - basicAuth:
        - repo-label:update
      description: 'Update a repository label name.


        Labels can be used to group and organize repositories and to apply security/license policies.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:update'
  /orgs/{org_slug}/repos/labels/{label_id}/label-setting:
    delete:
      tags:
      - repo-labels
      summary: Delete repository label setting (beta)
      operationId: deleteOrgRepoLabelSetting
      security:
      - bearerAuth:
        - repo-label:update
      - basicAuth:
        - repo-label:update
      description: 'Delete the setting (e.g. security/license policy) for a repository label.



        Note that repository label settings currently only support `issueRules`

        and `issueRulesPolicyDefault`. A policy is considered "active" for

        a given repository label if the `issueRulesPolicyDefault` is set,

        and inactive when not set. `issueRules` can be used to further

        refine the alert triage strategy.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:update'
    get:
      tags:
      - repo-labels
      summary: Get repository label setting (beta)
      operationId: getOrgRepoLabelSetting
      security:
      - bearerAuth:
        - repo-label:list
      - basicAuth:
        - repo-label:list
      description: 'Retrieve the setting (e.g. security/license policy) for a repository label.



        Note that repository label settings currently only support `issueRules`

        and `issueRulesPolicyDefault`. A policy is considered "active" for

        a given repository label if the `issueRulesPolicyDefault` is set,

        and inactive when not set. `issueRules` can be used to further

        refine the alert triage strategy.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:list'
    put:
      tags:
      - repo-labels
      summary: Update repository label setting (beta)
      operationId: updateOrgRepoLabelSetting
      security:
      - bearerAuth:
        - repo-label:update
      - basicAuth:
        - repo-label:update
      description: 'Update the setting (e.g. security/license policy) for a repository label.



        Note that repository label settings currently only support `issueRules`

        and `issueRulesPolicyDefault`. A policy is considered "active" for

        a given repository label if the `issueRulesPolicyDefault` is set,

        and inactive when not set. `issueRules` can be used to further

        refine the alert triage strategy.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:update'
  /orgs/{org_slug}/repos/labels/{label_id}/disassociate:
    post:
      tags:
      - repo-labels
      summary: Disassociate repository label (beta)
      operationId: disassociateOrgRepoLabel
      security:
      - bearerAuth:
        - repo-label:update
      - basicAuth:
        - repo-label:update
      description: 'Disassociate a repository label from a repository.


        Labels can be used to group and organize repositories and to apply security/license policies.


        This endpoint consumes 1 unit of your quota.


        This endpoint requires the following org token scopes:

        - repo-label:update'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      description: Organization Tokens can be passed as a Bearer token
    basicAuth:
      type: http
      scheme: basic
      description: Organization Tokens can be passed as the user field in basic auth
